[package]
name = "firnparser"
version = "0.1.0"
edition = "2018"

[lib]
crate_type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.14.0"
orgize = "0.8.3"
serde_json = "1.0.48"
